# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
dist: xenial

scala:
   - 2.12.6

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - pyrosrppltoo@gmail.com
jdk:
  - oraclejdk8

script:
  - sbt clean jacoco
  
after_success:
  - bash <(curl -s https://codecov.io/bash)